
#define SLK_UNSC() Selkie_UNSC_

//--------OPTRE-------
#define OPTRE() OPTRE_
#define STALLION() OPTRE()m1087_stallion_

//--- Use these

#define OPTRE_UNSC_STALLION_COVERED QUOTE(STALLION()cover_unsc)
#define OPTRE_UNSC_STALLION QUOTE(STALLION()unsc)

//--------Army--------
#define SLK_UNSC_ARMY() SLK_UNSC()Army_
#define SLK_UNSC_ARMY_MOD(var1) SLK_UNSC_ARMY()var1

//--- Use These

#define SLK_UNSC_ARMY_FALCON_UNARMED_WOODLAND QUOTE(SLK_UNSC_ARMY_MOD(Falcon_Unarmed_Woodland))
#define SLK_UNSC_ARMY_FALCON_ARMED_WOODLAND QUOTE(SLK_UNSC_ARMY_MOD(Falcon_Armed_Woodland))


//---

//--------MARINES--------
#define SLK_UNSC_MARINES() SLK_UNSC()Marines_
#define SLK_UNSC_MARINES_MOD(var1) SLK_UNSC_MARINES()var1

//--- Use These

#define SLK_UNSC_MARINES_HOG_UNARMED_WOODLAND QUOTE(SLK_UNSC_MARINES_MOD(Hog_Unarmed_Halo3))
#define SLK_UNSC_MARINES_HOG_LAAG_WOODLAND QUOTE(SLK_UNSC_MARINES_MOD(Hog_LAAG_Halo3))
#define SLK_UNSC_MARINES_HOG_GAUSS_WOODLAND QUOTE(SLK_UNSC_MARINES_MOD(Hog_Gauss_Halo3))
#define SLK_UNSC_MARINES_HORNET "Selkie_UNSC_Marines_Hornet_Halo3"

//Hogs


//Pelicans
#define SLK_UNSC_MARINES_PELICAN_UNARMED_WOODLAND QUOTE(SLK_UNSC_MARINES_MOD(Pelican_Unarmed_Halo3))
#define SLK_UNSC_MARINES_PELICAN_ARMED_WOODLAND QUOTE(SLK_UNSC_MARINES_MOD(Pelican_Armed_Halo3))
//---
