
#define SLK_UNSC() Selkie_UNSC_

//--------OPTRE-------
#define OPTRE() OPTRE_
#define OPTRE_STALLION() OPTRE()m1087_stallion_
#define OPTRE_ORYX() OPTRE()M493_

//--- Use these

#define OPTRE_UNSC_STALLION_COVERED QUOTE(OPTRE_STALLION()cover_unsc)
#define OPTRE_UNSC_STALLION QUOTE(OPTRE_STALLION()unsc)

#define OPTRE_ORYX_APC_AIE_RCWS QUOTE(OPTRE_ORYX()AIE_RCWS)
#define OPTRE_ORYX_APC_M37_RCWS QUOTE(OPTRE_ORYX()M37_RCWS)

#define OPTRE_SCORPION QUOTE(OPTRE()M808B_UNSC)
#define OPTRE_SCORPION_B QUOTE(OPTRE()M808BM_UNSC)

//--------Army--------
#define SLK_UNSC_ARMY() SLK_UNSC()Army_
#define SLK_UNSC_ARMY_MOD(var1) SLK_UNSC_ARMY()var1

//--- Use These

#define SLK_UNSC_ARMY_FALCON_UNARMED_WOODLAND QUOTE(SLK_UNSC_ARMY_MOD(Falcon_Unarmed_Woodland))
#define SLK_UNSC_ARMY_FALCON_ARMED_WOODLAND QUOTE(SLK_UNSC_ARMY_MOD(Falcon_Armed_WoodlandA))

//Turrets

#define SLK_UNSC_ARMY_TURRET_M247A1_WOODLAND QUOTE(SLK_UNSC_ARMY_MOD(StaticMG_M247A1_WoodlandB))
#define SLK_UNSC_ARMY_TURRET_M247H_WOODLAND QUOTE(SLK_UNSC_ARMY_MOD(StaticMG_M247H_WoodlandB))
#define SLK_UNSC_ARMY_TURRET_AA_WOODLAND QUOTE(SLK_UNSC_ARMY_MOD(Emplacement_AA_WoodlandB))
#define SLK_UNSC_ARMY_TURRET_AT_WOODLAND QUOTE(SLK_UNSC_ARMY_MOD(Emplacement_AT_WoodlandB))
#define SLK_UNSC_ARMY_TURRET_GAUSS_WOODLAND QUOTE(SLK_UNSC_ARMY_MOD(Emplacement_Gauss_WoodlandB))
#define SLK_UNSC_ARMY_TURRET_LAAG_WOODLAND QUOTE(SLK_UNSC_ARMY_MOD(Emplacement_LAAG_WoodlandB))

//---

//--------MARINES--------
#define SLK_UNSC_MARINES() SLK_UNSC()Marines_
#define SLK_UNSC_MARINES_MOD(var1) SLK_UNSC_MARINES()var1

//--- Use These

//Hogs
#define SLK_UNSC_MARINES_HOG_UNARMED_WOODLAND QUOTE(SLK_UNSC_MARINES_MOD(Hog_Unarmed_Halo3))
#define SLK_UNSC_MARINES_HOG_TRANSPORT_WOODLAND QUOTE(SLK_UNSC_MARINES_MOD(Hog_Transport_Halo3))
#define SLK_UNSC_MARINES_HOG_LAAG_WOODLAND QUOTE(SLK_UNSC_MARINES_MOD(Hog_LAAG_Halo3))
#define SLK_UNSC_MARINES_HOG_GAUSS_WOODLAND QUOTE(SLK_UNSC_MARINES_MOD(Hog_Gauss_Halo3))
#define SLK_UNSC_MARINES_HOG_AA_WOODLAND QUOTE(SLK_UNSC_MARINES_MOD(Hog_AA_Halo3))
#define SLK_UNSC_MARINES_HOG_AT_WOODLAND QUOTE(SLK_UNSC_MARINES_MOD(Hog_AT_Halo3))
#define SLK_UNSC_MARINES_HORNET QUOTE(SLK_UNSC_MARINES_MOD(Hornet_Halo3))

//Bison
#define SLK_UNSC_MARINES_BISON_50MM_WOODLAND QUOTE(SLK_UNSC_MARINES_MOD(Bison_50mm_Halo3))
#define SLK_UNSC_MARINES_BISON_105MM_WOODLAND QUOTE(SLK_UNSC_MARINES_MOD(Bison_105mm_Halo3))
#define SLK_UNSC_MARINES_BISON_UNARMED_WOODLAND QUOTE(SLK_UNSC_MARINES_MOD(Bison_Unarmed_Halo3))

//Oryx
#define SLK_UNSC_MARINES_ORYX_WOODLAND QUOTE(SLK_UNSC_MARINES_MOD(Oryx_Halo3))

//Pelicans
#define SLK_UNSC_MARINES_PELICAN_UNARMED_WOODLAND QUOTE(SLK_UNSC_MARINES_MOD(Pelican_Unarmed_Halo3))
#define SLK_UNSC_MARINES_PELICAN_ARMED_WOODLAND QUOTE(SLK_UNSC_MARINES_MOD(Pelican_Armed_Halo3))

//Turrets
//---
